# coding: utf-8

"""
    Bytrox Docs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api._____api import Api  # noqa: E501
from openapi_client.rest import ApiException


class TestApi(unittest.TestCase):
    """Api unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api._____api.Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_invoice_create_wallet_post(self):
        """Test case for invoice_create_wallet_post

        Создание статического кошелька  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
